services:
  - type: web
    name: proyecto-farmacia
    env: docker
    plan: free
    branch: maestro
    # Ya no necesitamos comandos especiales. Render usará el Dockerfile.
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: farmacia-db
          property: connectionString

databases:
  - name: farmacia-db
    plan: free