services:
  - type: web
    name: proyecto-farmacia
    # NOTA: No hay 'runtime' ni 'env: docker'. Render lo detectará como Java automáticamente.
    plan: free
    branch: maestro
    buildCommand: "mvn clean package"
    startCommand: "java -jar target/dependency/webapp-runner.jar --port $PORT target/*.war"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: farmacia-db
          property: connectionString

databases:
  - name: farmacia-db
    plan: free